version: "3.8"

services:
  mysqldb:
    image: mysql:8.0
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - "3306"
    volumes:
      - db:/var/lib/mysql
  app:
    depends_on:
      - mysqldb
    build: ./turnkey-app
    restart: on-failure
    env_file: ./.env
    ports:
      - "8080"
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://mysqldb:$MYSQLDB_DOCKER_PORT/$MYSQLDB_DATABASE?useSSL=false",
        "spring.datasource.username" : "$MYSQLDB_USER",
        "spring.datasource.password" : "$MYSQLDB_ROOT_PASSWORD",
        "spring.datasource.driver-class-name" : "com.mysql.cj.jdbc.Driver",
        "spring.jpa.hibernate.naming.physical-strategy" : "org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl",
        "spring.jpa.hibernate.ddl-auto" : "update",
        "spring.jpa.show-sql" : "true",
        "spring.jpa.properties.hibernate.format_sql" : "true",
        "spring.jpa.properties.hibernate.generate_statistics" : "false"
      }'
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true

volumes:
  db:
